#!/usr/bin/env bash
exec env QEMU_LOG="nochain" ./afl-qemu -display none -M cmu900 \
  -serial file:./syncdir/$1/stdout  -display none \
  -drive if=pflash,format=raw,index=0,file=./syncdir/$1/data/boot.bin \
  -drive if=pflash,format=raw,index=1,file=./syncdir/$1/data/app.bin \
  -drive if=pflash,format=raw,index=2,file=./syncdir/$1/data/data.bin \
  -device scripted-io,iobase=0x5000,iosize=1,const=0x80 \
  -device scripted-io,iobase=0x6000,iosize=1,const=0xFB \
  -afl-entry 0x1033734 -afl-start 0x0 -afl-end -1 \
  -afl-criu-dir /mnt/tmpfs/syncdir/$1/criu/ -afl-fuzzer-name $1 \
  -afl-state-files ./syncdir/$1/data/data.bin,./syncdir/$1/data/boot.bin,./syncdir/$1/data/app.bin

